### ISSUE TITLE
Исправить вывод сообщений в логах

### ISSUE THREAD

**Issue by CleanTalk** [CleanTalk/dle-antispam#3]
Денис, а когда поправите журнал? А то крокозябры добивают!!

30.05.2014 20:45:22 Р”РјРёС‚СЂРёР№Р’    5.228.14.228    Username: Р”РјРёС‚СЂРёР№Р’, email: pereslegin67@gmail.com. **\* Сообщение запрещено. Отправитель находится в черном списке. Включите JavaScript. Номер запроса 3876ffe85e0c8eefa8bc7bce9be4dba6. Антиспам сервис cleantalk.ru. ***

**Comment by svfcode** [comment]
Closed as not relevant
